version: "3.9"

services:
  # Renommage du service pour plus de clart√©
  keycloak-postgres:
    image: postgres:15-alpine
    container_name: keycloak-postgres-standalone
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - keycloak_standalone_data:/var/lib/postgresql/data
    networks:
      - keycloak-standalone-network
    healthcheck:
      # Utilise les variables pour le healthcheck
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-standalone
    command: start-dev --import-realm
    
    environment:
      KC_DB: postgres
      # Utilise la variable pour le nom de la BDD
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/${POSTGRES_DB}
      # Utilise les variables pour l'utilisateur et le mot de passe de la BDD
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      # Utilise les variables pour l'admin Keycloak
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8090 # Port interne au conteneur (ne pas changer)
    ports:
      # Utilise la variable pour le port d'exposition
      - "${KEYCLOAK_PORT}:8090"
      
    volumes:
      # Utilise la variable pour le chemin d'import
      - ${KEYCLOAK_IMPORT_PATH}:/opt/keycloak/data/import
      
    depends_on:
      keycloak-postgres:
        condition: service_healthy
        
    networks:
      - keycloak-standalone-network

volumes:
  keycloak_standalone_data:

networks:
  keycloak-standalone-network:
    driver: bridge